# Generated by Django 3.2.5 on 2021-07-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('group_profile', models.ImageField(default='default.jpg', upload_to='group_profile')),
                ('category', models.ManyToManyField(to='groupify.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(default='default.jpg', upload_to='user_profile')),
                ('about', models.CharField(max_length=250)),
                ('group', models.ManyToManyField(to='groupify.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('user_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='news_images')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupify.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupify.profile')),
            ],
        ),
    ]
